openapi: 3.0.1
info:
  title: 3d ingestion catalog
  description: Service to create 3d ingestion catalog
  version: 2.0.0
components:
  schemas:
    payload:
      type: object
      description: 3d tiles metadata payload
      required:
        - productName
        - productType
        - sourceDateStart
        - sourceDateEnd
        - maxAccuracyCE90
        - absoluteAccuracyLEP90
        - sensors
        - footprint
        - srsName
        - region
        - classification
        - productionSystem
        - productionSystemVer
        - producerName
      properties:
        productId:
          type: string
          nullable: true
          default: null
          description: ID of product
        productName:
          type: string
          maxLength: 50
          description: Name of product
        productType:
          type: string
          description: Type of product (3DPhotoRealistic)
          example: 3DPhotoRealistic
        description:
          type: string
          maxLength: 250
          nullable: true
          description: description and comments
        creationDate:
          type: string
          format: date-time
          nullable: true
          description: Creation date
        sourceDateStart:
          type: string
          format: date-time
          description: Oldest date of taken photo
        sourceDateEnd:
          type: string
          format: date-time
          description: Newest date of taken photo
        minResolutionMeter:
          type: number
          format: double
          nullable: true
          example: 1.1
          minimum: 0.01
          maximum: 8000
          description: Minimum resolution in meters
        maxResolutionMeter:
          type: number
          format: double
          nullable: true
          example: 1.5
          minimum: 0.01
          maximum: 8000
          description: Maximum resolution in meters
        nominalResolution:
          type: number
          format: double
          nullable: true
          example: 5
          minimum: 0
          description: Number of points in one size unit
        maxAccuracyCE90:
          type: number
          format: double
          minimum: 0
          description: Maximum absolute horizontal accuracy
        absoluteAccuracyLEP90:
          type: number
          format: double
          minimum: 0
          maximum: 999
          description: Absolute vertical accuracy
        accuracySE90:
          type: number
          format: double
          minimum: 0
          nullable: true
          maximum: 250
          description: Absolute spherical accuracy
        relativeAccuracyLEP90:
          type: number
          format: double
          nullable: true
          minimum: 0
          maximum: 100
          description: Relative vertical accuracy
        visualAccuracy:
          type: number
          format: double
          nullable: true
          minimum: 0
          maximum: 100
          description: Measure of visual quality
        sensors:
          type: array
          items:
            type: string
          description: Layer sensors list 
          example: OTHER
        footprint:
          $ref: ../geojson.yaml#/components/schemas/Geometry
          description: Geographic demarkatetion of the product
          example: '{"type":"Polygon","coordinates":[[[1,2],[3,4],[5,6],[7,8],[1,2]]]}'
        heightRangeFrom:
          type: number
          format: double
          nullable: true
          description: Minimum height range of ground
        heightRangeTo:
          type: number
          format: double
          nullable: true
          description: Maximum height range of ground
        srsId:
          type: integer
          example: 4326
          nullable: true
          description: ID of srs
        srsName:
          type: string
          description: Name of the srsID
        srsOrigin:
          type: string
          nullable: true
          example: (30;40;50)
          pattern: ^\(([-]?(0|[1-9]\d*)(\.\d+)?;){2}[-]?(0|[1-9]\d*)(\.\d+)?\)$
          description: First of axes
        region:
          type: array
          items:
            type: string
          description: regions included in the layer
        classification:
          type: string
          example: '5'
          pattern: ^[0-9]$
          description: Classification of the product
        productionSystem:
          type: string
          description: Production system
        productionSystemVer:
          type: string
          maxLength: 20
          description: Version production system
        producerName:
          type: string
          description: The name of the producer (product owner)
        productionMethod:
          type: string
          nullable: true
          description: Method of the production
        minFlightAlt:
          type: number
          format: double
          description: Minimum height of the flight
        maxFlightAlt:
          type: number
          nullable: true
          format: double
          description: Maximum height of the flight
        geographicArea:
          type: string
          nullable: true
          description: Area inside the region
    catalog-payload:
      type: object
      description: 3d tiles metadata payload with links
      required:
        - "links"
      allOf:
        - $ref: "#/components/schemas/payload"
        - properties:
            links:
              type: array
              items:
                $ref: ../link.yaml#/components/schemas/Link      
    metadata:  
      type: object
      description: 3d tiles catalog metadata payload
      allOf:
        - $ref: "#/components/schemas/catalog-payload"
        - properties:
            identifier:
              type: string
            productBoundingBox:
              type: string
              readOnly: true
              pattern: ^([-+]?(0|[1-9]\d*)(\.\d+)?,){3}[-+]?(0|[1-9]\d*)(\.\d+)?$
              description: The bounding box of the product
            productVersion:
              type: integer
              example: 1
              description: Number of version
              readOnly: true
            insertDate:
              type: string
              description: Insertion date
              format: date-time
              readOnly: true
            updateDate:
              type: string
              description: Update date
              format: date-time
              readOnly: true
              nullable: true
    updatePayload:
      type: object
      description: 3d tiles metadata update payload
      properties:
        title:
          type: string
          description: Title
        description:
          type: string
          description: Description
        classification:
          type: string
          description: Product classification
        sensorType:
          type: string
          description: The sensor used as the source of the product
