openapi: "3.0.1"
info:
  title: layer metadata definitions
  version: 1.0.0
components:
  schemas:
    updateRasterLayerMetadata:
      type: object
      required:
        - classification
      description: layer metadata that will override
      properties:
        classification:
          type: string
          description: Permitted roles
          pattern: ^[0-9]$|^[1-9][0-9]$|^(100)$
    newRasterLayerMetadata:
      type: object
      required:
        - productId
        - productName
        - productType
        - srs
        - srsName
        - transparency
        - region
      allOf:
        - $ref: '#/components/schemas/updateRasterLayerMetadata'
        - $ref: '#/components/schemas/RasterLayerBaseMetadata'
        - properties:
            productName:
              type: string
              description: Layer's external name
            productSubType:
              type: string
              description: Layer's sub type
            region:
              type: array
              items:
                type: string
              description: region of record
            srs:
              type: string
              enum:
                - '4326'
              description: geo system id
            srsName:
              type: string
              enum:
                - WGS84GEO
              description: geo system name
            transparency:
              type: string
              enum:
                - TRANSPARENT
                - OPAQUE
              description: layer can be transparent or opaque
            producerName:
              type: string
              description: creator name default IDFMU
            scale:
              type: integer
              minimum: 0
              maximum: 100000000
            description:
              type: string
              description: layer's description
    RasterLayerBaseMetadata:
      required:
        - productId
        - productType
      properties:
        productId:
          type: string
          description: layer's external identifier
          pattern: ^[A-Za-z]{1}[A-Za-z0-9_]{0,37}$
          example: BLUE_MARBLE
        productType:
          $ref: '#/components/schemas/productType'
    productType:
      type: string
      enum:
        - Orthophoto
        - OrthophotoHistory
        - OrthophotoBest
        - RasterMap
        - RasterMapBest
        - RasterAid
        - RasterAidBest
        - RasterVector
        - RasterVectorBest
      description: layer's type might be derived from the first letter
