openapi: "3.0.1"
info:
  title: layer metadata definitions
  version: 1.0.0
components:
  schemas:
    updateRasterLayerMetadata:
      type: object
      required:
        - classification
      description: layer metadata that will override
      properties:
        description:
          type: string
          description: layer's description
        classification:
          type: string
          description: Permitted roles
    newRasterLayerMetadata:
      type: object
      required:
        - productId
        - productName
        - productType
        - srs
        - srsName
        - transparency
        - region
      allOf:
        - $ref: '#/components/schemas/updateRasterLayerMetadata'
        - properties:
            productId:
              type: string
              description: Layer's external identifier
              pattern: ^[a-zA-Z0-9_-]+$
            productName:
              type: string
              description: Layer's external name
            productType:
              $ref: '#/components/schemas/productType'
            productSubType:
              type: string
              description: Layer's sub type  
            region:
              type: array
              items:
                type: string
              description: region of record  
            srs:
              type: string
              enum: 
                - '4326'
              description: geo system id
            srsName:
              type: string
              enum:
                - WGS84Geo
              description: geo system name
            transparency:
              type: string
              enum:
                - TRANSPARENT
                - OPAQUE
              description: layer can be transparent or opaque
            producerName:
              type: string
              description: creator name default IDFMU  
            scale:
              type: integer
              minimum: 0
              maximum: 100000000                                        
    productType:
      type: string
      enum:
        - Orthophoto
        - OrthophotoHistory
        - OrthophotoBest
        - RasterMap
        - RasterMapBest
        - RasterAid
        - RasterAidBest
        - RasterVector
        - RasterVectorBest
      description: layer's type might be derived from the first letter
