openapi: "3.0.1"
info:
  title: Layer polygon part
  version: 1.0.0
components:
  schemas:
    polygonPartsMetadata:
      type: array
      items:
        $ref: '#/components/schemas/polygonPartMetadata'
      minItems: 1
      description: polygon parts data
    polygonPartMetadata:
      type: object
      description: Layer polygon part data definitions
      required:
        - sourceName
        - imagingTimeBeginUTC
        - imagingTimeEndUTC
        - footprint
        - resolutionDegree
        - resolutionMeter
        - sourceResolutionMeter
        - horizontalAccuracyCE90
        - sensors
      properties:
        sourceId:
          type: string
          description: Layer's external identifier
        sourceName:
          type: string
          description: Layer's external name
        imagingTimeBeginUTC:
          type: string
          description: Oldest imaging date (UTC)
          format: date-time
        imagingTimeEndUTC:
          type: string
          description: Latest imaging date (UTC)
          format: date-time
        resolutionDegree:
          type: number
          minimum: 1.67638e-7
          maximum: 0.703125
          format: double
          description: Resolution of layer in degrees/pixel
        resolutionMeter:
          type: number
          minimum: 0.0185
          maximum: 78271.52
          format: double
          description: Resolution of layer in meters
        sourceResolutionMeter:
          type: number
          minimum: 0.0185
          maximum: 78271.52
          format: double
          description: Resolution of layer in meters
        horizontalAccuracyCE90:
          type: number
          minimum: 0.01
          maximum: 4000
          format: double
          description: Horizontal accuracy
        sensors:
          type: array
          items:
            type: string
            pattern: ^(?! ).+(?<! )$
          minItems: 1
          description: Layer sensors list
        countries:
          type: array
          items:
            type: string
          description: Countries included in the part
        cities:
          type: array
          items:
            type: string
          description: Cities included in the part
        description:
          type: string
        footprint:
          $ref: '../../geojson.yaml#/components/schemas/Polygon'
          description: Part polygonal footprint
