openapi: "3.0.1"
info:
  title: Raster layer definitions
  version: 1.0.0
components:
  schemas:
    NewRasterLayer:
      type: object
      properties:
        metadata:
          $ref: './metadata/rasterLayerMetadata.yaml#/components/schemas/newRasterLayerMetadata'
        partsData:
          $ref: './partData/rasterLayerPartData.yaml#/components/schemas/polygonPartsMetadata'
        inputFiles:
          $ref: './inputFiles/rasterLayerInputFiles.yaml#/components/schemas/InputFiles'
    UpdateRasterLayer:
      type: object
      properties:
        metadata:
          $ref: './metadata/rasterLayerMetadata.yaml#/components/schemas/updateRasterLayerMetadata'
        partsData:
          $ref: './partData/rasterLayerPartData.yaml#/components/schemas/polygonPartsMetadata'
        inputFiles:
          $ref: './inputFiles/rasterLayerInputFiles.yaml#/components/schemas/InputFiles'
