openapi: "3.0.1"
info:
  title: Layer ingestion parameters definitions
  version: 1.0.0
components:
  schemas:
    IngestionParams:
      type: object
      description: ingestion parameters
      required:
        - metadata
        - originDirectory
        - fileNames
      properties:
        metadata:
          $ref: '../insertLayerMetadata.yaml#/components/schemas/insertLayerMetadata'
        originDirectory:
          type: string
          description: layer source directory
        fileNames:
          type: array
          description: layer sources
          items:
            type: string
            pattern: ^.+\.[Gg][Pp][Kk][Gg]$
