import { GeoJSON } from 'geojson';
import { RecordType, ProductType, RecordStatus } from '@map-colonies/types';
import { IPropCatalogDBMapping } from '../common/interfaces/propCatalogDBMapping.interface';
import { graphql } from '../common/decorators/graphQL/graphql.decorator';
import {
  FieldCategory,
  fieldConfig,
  getFieldConfig,
  IFieldConfigInfo,
  IPropFieldConfigInfo,
} from '../common/decorators/fieldConfig/fieldConfig.decorator';
import type { AreaOrPoint, DEMDataType, VerticalType } from '../pycsw/types';
import { IMetadataCommonModel } from './interfaces/metadataCommonModel';
import { getPyCSWMapping, IPYCSWMapping, pycsw } from './decorators/property/csw.decorator';
import { getCatalogDBMapping, ICatalogDBMapping, catalogDB } from './decorators/property/catalogDB.decorator';
import { getTsTypesMapping, tsTypes, TsTypes } from './decorators/property/tsTypes.decorator';

export interface ILayerMetadata {
  acquisitionTimeBeginUTC: Date;
  acquisitionTimeEndUTC: Date;
  areaOrPoint: AreaOrPoint;
  dataType: DEMDataType;
  displayPath: string;
  ingestionDateUTC: Date;
  maxAbsoluteAccuracyLEP90: number | undefined;
  maxHorizontalAccuracyCEP90: number | undefined;
  maxRelativeAccuracyLEP90: number | undefined;
  maxResolutionDegree: number;
  maxResolutionMeter: number;
  minAbsoluteAccuracyLEP90: number | undefined;
  minHorizontalAccuracyCEP90: number | undefined;
  minRelativeAccuracyLEP90: number | undefined;
  minResolutionDegree: number;
  minResolutionMeter: number;
  noDataValue: number;
  productStatus: RecordStatus;
  productSubType: string | undefined;
  productVersion: number;
  srsId: number;
  updateDateUTC: Date;
  verticalSrsId: number;
  verticalSrsName: string;
  verticalType: VerticalType;
}

export interface IPropPYCSWMapping extends IPYCSWMapping {
  prop: string;
}

export type DEMProductType = ProductType.DSM | ProductType.DTM;
export type DEMProductTypes = { [K in keyof Pick<IMetadataCommonModel, 'productType'>]: DEMProductType };
export type DEMMetadataCommonModel = Omit<IMetadataCommonModel, 'productTypes'>;

export class LayerDemMetadata implements ILayerMetadata, DEMMetadataCommonModel, DEMProductTypes {
  //#region COMMON FIELDS
  //#region CORE: id
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:id',
    queryableField: 'mc:id',
    pycswField: 'pycsw:Identifier',
  })
  @catalogDB({
    column: {
      name: 'identifier',
      type: 'text',
      nullable: false,
      primary: true,
    },
  })
  @tsTypes({
    mappingType: TsTypes.STRING,
  })
  @graphql()
  @fieldConfig({
    category: FieldCategory.MAIN,
    isAutoGenerated: true,
  })
  //#endregion
  public id!: string;

  //#region COMMON: type
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:type',
    queryableField: 'mc:type',
    pycswField: 'pycsw:Type',
  })
  @catalogDB({
    column: {
      name: 'type',
      type: 'text',
      nullable: false,
    },
  })
  @tsTypes({
    mappingType: TsTypes.RECORDTYPE,
  })
  @graphql({
    nullable: true,
  })
  //#endregion
  public type: RecordType = RecordType.RECORD_DEM;

  //#region COMMON: classification
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:classification',
    queryableField: 'mc:classification',
    pycswField: 'pycsw:Classification',
  })
  @catalogDB({
    column: {
      name: 'classification',
      type: 'text',
      nullable: false,
    },
  })
  @tsTypes({
    mappingType: TsTypes.STRING,
  })
  @graphql({
    nullable: false,
  })
  @fieldConfig({
    category: FieldCategory.GENERAL,
    infoMsgCode: ['info-general-tooltip.required'],
    lookupTable: 'classification',
    validation: [
      {
        errorMsgCode: 'validation-general.required',
        required: true,
      },
    ],
  })
  //#endregion
  public classification!: string;

  //#region COMMON: productName
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:productName',
    queryableField: 'mc:productName',
    pycswField: 'pycsw:Title',
  })
  @catalogDB({
    column: {
      name: 'product_name',
      type: 'text',
      nullable: false,
    },
  })
  @tsTypes({
    mappingType: TsTypes.STRING,
  })
  @graphql()
  @fieldConfig({
    category: FieldCategory.MAIN,
    infoMsgCode: ['info-general-tooltip.required'],
    validation: [
      {
        errorMsgCode: 'validation-general.required',
        required: true,
      },
    ],
  })
  //#endregion
  public productName!: string;

  //#region COMMON: description
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:description',
    queryableField: 'mc:description',
    pycswField: 'pycsw:Abstract',
  })
  @catalogDB({
    column: {
      name: 'description',
      type: 'text',
      nullable: true,
    },
  })
  @tsTypes({
    mappingType: TsTypes.STRING,
  })
  @graphql({
    nullable: true,
  })
  @fieldConfig({
    category: FieldCategory.GENERAL,
  })
  //#endregion
  public description: string | undefined = undefined;

  //#region COMMON: srsId
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:srsId',
    queryableField: 'mc:srsId',
    pycswField: 'pycsw:CRS',
  })
  @catalogDB({
    column: {
      name: 'srs_id',
      type: 'number',
      nullable: false,
    },
  })
  @tsTypes({
    mappingType: TsTypes.NUMBER,
  })
  @graphql({
    nullable: false,
  })
  @fieldConfig({
    category: FieldCategory.GEO_INFO,
    isAutoGenerated: true,
  })
  //#endregion
  public srsId!: number;

  //#region COMMON: srsName
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:srsName',
    queryableField: 'mc:srsName',
    pycswField: 'pycsw:CRSName',
  })
  @catalogDB({
    column: {
      name: 'srs_name',
      type: 'text',
      nullable: false,
    },
  })
  @tsTypes({
    mappingType: TsTypes.STRING,
  })
  @graphql({
    nullable: false,
  })
  @fieldConfig({
    category: FieldCategory.GEO_INFO,
    isAutoGenerated: true,
  })
  //#endregion
  public srsName!: string;

  //#region COMMON: producerName
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:producerName',
    queryableField: 'mc:producerName',
    pycswField: 'pycsw:Creator',
  })
  @catalogDB({
    column: {
      name: 'producer_name',
      type: 'text',
      default: 'IDFMU',
      nullable: true,
    },
  })
  @tsTypes({
    mappingType: TsTypes.STRING,
  })
  @graphql({
    nullable: false,
  })
  @fieldConfig({
    category: FieldCategory.GENERAL,
    default: 'IDFMU',
  })
  //#endregion
  public producerName = 'IDFMU';

  //#region DEM: ingestionDateUTC
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:ingestionDateUTC',
    queryableField: 'mc:ingestionDateUTC',
    pycswField: 'pycsw:ingestionDateUTC',
  })
  @catalogDB({
    column: {
      name: 'ingestion_date_utc',
      type: 'timestamp with time zone',
      nullable: false,
    },
  })
  @tsTypes({
    mappingType: TsTypes.DATE,
  })
  @graphql({
    nullable: true,
  })
  @fieldConfig({
    category: FieldCategory.MAIN,
    isAutoGenerated: true,
  })
  //#endregion
  public ingestionDateUTC!: Date;

  //#region COMMON: updateDateUTC
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:updateDateUTC',
    queryableField: 'mc:updateDateUTC',
    pycswField: 'pycsw:updateDateUTC',
  })
  @catalogDB({
    column: {
      name: 'update_date_utc',
      type: 'timestamp with time zone',
      nullable: false,
    },
  })
  @tsTypes({
    mappingType: TsTypes.DATE,
  })
  @graphql({
    nullable: true,
  })
  @fieldConfig({
    category: FieldCategory.MAIN,
    isAutoGenerated: true,
  })
  //#endregion
  public updateDateUTC!: Date;

  //#region COMMON: acquisitionTimeBeginUTC
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:acquisitionTimeBeginUTC',
    queryableField: 'mc:acquisitionTimeBeginUTC',
    pycswField: 'pycsw:TempExtent_begin',
  })
  @catalogDB({
    column: {
      name: 'acquisition_time_begin_utc',
      type: 'timestamp with time zone',
      nullable: false,
    },
  })
  @tsTypes({
    mappingType: TsTypes.DATE,
  })
  @graphql({
    nullable: false,
  })
  @fieldConfig({
    category: FieldCategory.GENERAL,
    infoMsgCode: ['info-general-tooltip.required', 'info-field-tooltip.acquisitionTimeBeginUTC.max'],
    validation: [
      {
        errorMsgCode: 'validation-general.required',
        required: true,
      },
      {
        errorMsgCode: 'validation-field.acquisitionTimeBeginUTC.max',
        valueType: 'field',
        max: 'acquisitionTimeEndUTC',
      },
    ],
  })
  //#endregion
  public acquisitionTimeBeginUTC!: Date;

  //#region COMMON: acquisitionTimeEndUTC
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:acquisitionTimeEndUTC',
    queryableField: 'mc:acquisitionTimeEndUTC',
    pycswField: 'pycsw:TempExtent_end',
  })
  @catalogDB({
    column: {
      name: 'acquisition_time_end_utc',
      type: 'timestamp with time zone',
      nullable: false,
    },
  })
  @tsTypes({
    mappingType: TsTypes.DATE,
  })
  @graphql({
    nullable: false,
  })
  @fieldConfig({
    category: FieldCategory.GENERAL,
    infoMsgCode: ['info-general-tooltip.required'],
    validation: [
      {
        errorMsgCode: 'validation-general.required',
        required: true,
      },
    ],
  })
  //#endregion
  public acquisitionTimeEndUTC!: Date;

  //#region COMMON: sensors
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:sensors',
    queryableField: 'mc:sensors',
    pycswField: 'pycsw:sensorType',
  })
  @catalogDB({
    column: {
      name: 'sensors',
      type: 'text',
      nullable: false,
    },
    field: {
      overrideType: TsTypes.STRING,
    },
  })
  @tsTypes({
    mappingType: TsTypes.STRING_ARRAY,
  })
  @graphql({
    nullable: false,
  })
  @fieldConfig({
    category: FieldCategory.GENERAL,
    infoMsgCode: ['info-field-tooltip.sensors.tooltip'],
  })
  //#endregion
  public sensors!: string[];

  //#region COMMON: region
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:region',
    queryableField: 'mc:region',
    pycswField: 'pycsw:Region',
  })
  @catalogDB({
    column: {
      name: 'region',
      type: 'text',
      nullable: false,
    },
    field: {
      overrideType: TsTypes.STRING,
    },
  })
  @tsTypes({
    mappingType: TsTypes.STRING_ARRAY,
  })
  @graphql({
    nullable: false,
  })
  @fieldConfig({
    category: FieldCategory.GENERAL,
    infoMsgCode: ['info-field-tooltip.region.tooltip', 'info-general-tooltip.required'],
    isMultiSelection: true,
    lookupTable: 'countries',
    validation: [
      {
        errorMsgCode: 'validation-general.required',
        required: true,
      },
    ],
  })
  //#endregion
  public region!: string[];

  //#region COMMON: productId
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:productId',
    queryableField: 'mc:productId',
    pycswField: 'pycsw:ProductId',
  })
  @catalogDB({
    column: {
      name: 'product_id',
      type: 'text',
      nullable: false,
    },
  })
  @tsTypes({
    mappingType: TsTypes.STRING,
  })
  @graphql({
    nullable: true,
  })
  @fieldConfig({
    category: FieldCategory.MAIN,
    infoMsgCode: ['info-field-tooltip.productId.tooltip', 'info-general-tooltip.required'],
    validation: [
      {
        errorMsgCode: 'validation-general.required',
        required: true,
      },
    ],
  })
  //#endregion
  public productId!: string;

  //#region COMMON: productType
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:productType',
    queryableField: 'mc:productType',
    pycswField: 'pycsw:ProductType',
  })
  @catalogDB({
    column: {
      name: 'product_type',
      type: 'product_type',
      nullable: false,
      default: ProductType.DTM,
    },
  })
  @tsTypes({
    mappingType: TsTypes.PRODUCTTYPE,
  })
  @graphql()
  @fieldConfig({
    category: FieldCategory.MAIN,
    infoMsgCode: ['info-general-tooltip.required'],
    validation: [
      {
        errorMsgCode: 'validation-general.required',
        required: true,
      },
    ],
  })
  //#endregion
  public productType: DEMProductType = ProductType.DTM;

  //#region COMMON: productSubType
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:productSubType',
    queryableField: 'mc:productSubType',
    pycswField: 'pycsw:ProductSubType',
  })
  @catalogDB({
    column: {
      name: 'product_sub_type',
      type: 'text',
      nullable: true,
    },
  })
  @tsTypes({
    mappingType: TsTypes.STRING,
  })
  @graphql()
  @fieldConfig({
    category: FieldCategory.MAIN,
    infoMsgCode: ['info-general-tooltip.required'],
    validation: [
      {
        errorMsgCode: 'validation-general.required',
        required: false,
      },
    ],
  })
  //#endregion
  public productSubType: string | undefined = undefined;

  //#region COMMON: productVersion
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:productVersion',
    queryableField: 'mc:productVersion',
    pycswField: 'pycsw:productVersion',
  })
  @catalogDB({
    column: {
      name: 'product_version',
      type: 'number',
      nullable: false,
      default: '1', //TODO: the type does not support number
    },
  })
  @tsTypes({
    mappingType: TsTypes.NUMBER,
  })
  @graphql()
  @fieldConfig({
    category: FieldCategory.MAIN,
    infoMsgCode: ['info-general-tooltip.required'],
    validation: [
      {
        errorMsgCode: 'validation-general.required',
        required: true,
      },
    ],
  })
  //#endregion
  public productVersion = 1;

  //#region COMMON: footprint
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:footprint',
    queryableField: 'mc:footprint',
    pycswField: 'pycsw:footprint',
  })
  @catalogDB({
    column: {
      name: 'footprint_geojson',
      type: 'text',
      nullable: false,
    },
  })
  @tsTypes({
    mappingType: TsTypes.OBJECT,
  })
  @graphql({
    nullable: false,
  })
  @fieldConfig({
    category: FieldCategory.GEO_INFO,
    infoMsgCode: ['info-general-tooltip.required'],
    validation: [
      {
        errorMsgCode: 'validation-general.required',
        required: true,
      },
      {
        errorMsgCode: 'validation-field.footprint.json',
        json: true,
      },
    ],
  })
  //#endregion
  public footprint!: GeoJSON;
  //#endregion

  //#region DEM SPECIFIC FIELDS
  //#region DEM: minAbsoluteAccuracyLEP90
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:minAbsoluteAccuracyLEP90',
    queryableField: 'mc:minAbsoluteAccuracyLEP90',
    pycswField: 'pycsw:minAbsoluteAccuracyLEP90',
  })
  @catalogDB({
    column: {
      name: 'min_absolute_accuracy_lep_90',
      type: 'numeric',
      nullable: true,
    },
  })
  @tsTypes({
    mappingType: TsTypes.NUMBER,
  })
  @graphql({
    nullable: false,
  })
  @fieldConfig({
    category: FieldCategory.GEO_INFO,
    infoMsgCode: ['info-general-tooltip.required'],
    validation: [
      {
        errorMsgCode: 'validation-general.required',
        required: false,
      },
    ],
  })
  //#endregion
  public minAbsoluteAccuracyLEP90: number | undefined = undefined;

  //#region DEM: maxAbsoluteAccuracyLEP90
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:maxAbsoluteAccuracyLEP90',
    queryableField: 'mc:maxAbsoluteAccuracyLEP90',
    pycswField: 'pycsw:maxAbsoluteAccuracyLEP90',
  })
  @catalogDB({
    column: {
      name: 'max_absolute_accuracy_lep_90',
      type: 'numeric',
      nullable: true,
    },
  })
  @tsTypes({
    mappingType: TsTypes.NUMBER,
  })
  @graphql({
    nullable: false,
  })
  @fieldConfig({
    category: FieldCategory.GEO_INFO,
    infoMsgCode: ['info-general-tooltip.required'],
    validation: [
      {
        errorMsgCode: 'validation-general.required',
        required: false,
      },
    ],
  })
  //#endregion
  public maxAbsoluteAccuracyLEP90: number | undefined = undefined;

  //#region DEM: minRelativeAccuracyLEP90
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:minRelativeAccuracyLEP90',
    queryableField: 'mc:minRelativeAccuracyLEP90',
    pycswField: 'pycsw:minRelativeAccuracyLEP90',
  })
  @catalogDB({
    column: {
      name: 'min_relative_accuracy_lep_90',
      type: 'numeric',
      nullable: true,
    },
  })
  @tsTypes({
    mappingType: TsTypes.NUMBER,
  })
  @graphql({
    nullable: true,
  })
  @fieldConfig({
    category: FieldCategory.GEO_INFO,
    infoMsgCode: ['info-general-tooltip.required'],
    validation: [
      {
        errorMsgCode: 'validation-general.required',
        required: false,
      },
    ],
  })
  //#endregion
  public minRelativeAccuracyLEP90: number | undefined = undefined;

  //#region DEM: maxRelativeAccuracyLEP90
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:maxRelativeAccuracyLEP90',
    queryableField: 'mc:maxRelativeAccuracyLEP90',
    pycswField: 'pycsw:maxRelativeAccuracyLEP90',
  })
  @catalogDB({
    column: {
      name: 'max_relative_accuracy_lep_90',
      type: 'numeric',
      nullable: true,
    },
  })
  @tsTypes({
    mappingType: TsTypes.NUMBER,
  })
  @graphql({
    nullable: true,
  })
  @fieldConfig({
    category: FieldCategory.GEO_INFO,
    infoMsgCode: ['info-general-tooltip.required'],
    validation: [
      {
        errorMsgCode: 'validation-general.required',
        required: false,
      },
    ],
  })
  //#endregion
  public maxRelativeAccuracyLEP90: number | undefined = undefined;

  //#region DEM: minResolutionDegree
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:minResolutionDegree',
    queryableField: 'mc:minResolutionDegree',
    pycswField: 'pycsw:minResolutionDegree',
  })
  @catalogDB({
    column: {
      name: 'min_resolution_degree',
      type: 'numeric',
      nullable: false,
    },
  })
  @tsTypes({
    mappingType: TsTypes.NUMBER,
  })
  @graphql({
    nullable: true,
  })
  @fieldConfig({
    category: FieldCategory.MAIN,
    isAutoGenerated: true,
    infoMsgCode: ['info-field-tooltip.minResolutionDegree.tooltip'],
  })
  //#endregion
  public minResolutionDegree!: number;

  //#region DEM: maxResolutionDegree
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:maxResolutionDegree',
    queryableField: 'mc:maxResolutionDegree',
    pycswField: 'pycsw:maxResolutionDegree',
  })
  @catalogDB({
    column: {
      name: 'max_resolution_degree',
      type: 'numeric',
      nullable: false,
    },
  })
  @tsTypes({
    mappingType: TsTypes.NUMBER,
  })
  @graphql({
    nullable: true,
  })
  @fieldConfig({
    category: FieldCategory.MAIN,
    isAutoGenerated: true,
    infoMsgCode: ['info-field-tooltip.maxResolutionDegree.tooltip'],
  })
  //#endregion
  public maxResolutionDegree!: number;

  //#region DEM: minResolutionMeter
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:minResolutionMeter',
    queryableField: 'mc:minResolutionMeter',
    pycswField: 'pycsw:minResolutionMeter',
  })
  @catalogDB({
    column: {
      name: 'min_resolution_meter',
      type: 'numeric',
      nullable: false,
    },
  })
  @tsTypes({
    mappingType: TsTypes.NUMBER,
  })
  @graphql({
    nullable: false,
  })
  @fieldConfig({
    category: FieldCategory.MAIN,
    isAutoGenerated: true,
    infoMsgCode: ['info-field-tooltip.minResolutionMeter.tooltip'],
  })
  //#endregion
  public minResolutionMeter!: number;

  //#region DEM: maxResolutionMeter
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:maxResolutionMeter',
    queryableField: 'mc:maxResolutionMeter',
    pycswField: 'pycsw:maxResolutionMeter',
  })
  @catalogDB({
    column: {
      name: 'max_resolution_meter',
      type: 'numeric',
      nullable: false,
    },
  })
  @tsTypes({
    mappingType: TsTypes.NUMBER,
  })
  @graphql({
    nullable: false,
  })
  @fieldConfig({
    category: FieldCategory.MAIN,
    isAutoGenerated: true,
    infoMsgCode: ['info-field-tooltip.maxResolutionMeter.tooltip'],
  })
  //#endregion
  public maxResolutionMeter!: number;

  //#region DEM: minHorizontalAccuracyCEP90
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:minHorizontalAccuracyCEP90',
    queryableField: 'mc:minHorizontalAccuracyCEP90',
    pycswField: 'pycsw:minHorizontalAccuracyCEP90',
  })
  @catalogDB({
    column: {
      name: 'min_horizontal_accuracy_cep_90',
      type: 'numeric',
      nullable: true,
    },
  })
  @tsTypes({
    mappingType: TsTypes.NUMBER,
  })
  @graphql({
    nullable: true,
  })
  @fieldConfig({
    category: FieldCategory.MAIN,
    isFilterable: true,
    infoMsgCode: ['info-field-tooltip.minHorizontalAccuracyCEP90.tooltip'],
  })
  //#endregion
  public minHorizontalAccuracyCEP90: number | undefined = undefined;

  //#region DEM: maxHorizontalAccuracyCEP90
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:maxHorizontalAccuracyCEP90',
    queryableField: 'mc:maxHorizontalAccuracyCEP90',
    pycswField: 'pycsw:maxHorizontalAccuracyCEP90',
  })
  @catalogDB({
    column: {
      name: 'max_horizontal_accuracy_cep_90',
      type: 'numeric',
      nullable: true,
    },
  })
  @tsTypes({
    mappingType: TsTypes.NUMBER,
  })
  @graphql({
    nullable: true,
  })
  @fieldConfig({
    category: FieldCategory.MAIN,
    isFilterable: true,
    infoMsgCode: ['info-field-tooltip.maxHorizontalAccuracyCEP90.tooltip'],
  })
  //#endregion
  public maxHorizontalAccuracyCEP90: number | undefined = undefined;

  //#region DEM: verticalType
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:verticalType',
    queryableField: 'mc:verticalType',
    pycswField: 'pycsw:verticalType',
  })
  @catalogDB({
    column: {
      name: 'vertical_type',
      type: 'vertical_type',
      nullable: false,
    },
  })
  @tsTypes({
    mappingType: TsTypes.STRING,
  })
  @graphql({
    nullable: false,
  })
  @fieldConfig({
    category: FieldCategory.GEO_INFO,
    infoMsgCode: ['info-general-tooltip.required'],
    validation: [
      {
        errorMsgCode: 'validation-general.required',
        required: true,
      },
    ],
  })
  //#endregion
  public verticalType!: VerticalType;

  //#region DEM: verticalSrsId
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:verticalSrsId',
    queryableField: 'mc:verticalSrsId',
    pycswField: 'pycsw:verticalSrsId',
  })
  @catalogDB({
    column: {
      name: 'vertical_srs_id',
      type: 'integer',
      nullable: false,
    },
  })
  @tsTypes({
    mappingType: TsTypes.NUMBER,
  })
  @graphql({
    nullable: false,
  })
  @fieldConfig({
    category: FieldCategory.GEO_INFO,
    infoMsgCode: ['info-general-tooltip.required'],
    validation: [
      {
        errorMsgCode: 'validation-general.required',
        required: true,
      },
    ],
  })
  //#endregion
  public verticalSrsId!: number;

  //#region DEM: verticalSrsName
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:verticalSrsName',
    queryableField: 'mc:verticalSrsName',
    pycswField: 'pycsw:verticalSrsName',
  })
  @catalogDB({
    column: {
      name: 'vertical_srs_name',
      type: 'text',
      nullable: false,
    },
  })
  @tsTypes({
    mappingType: TsTypes.STRING,
  })
  @graphql({
    nullable: false,
  })
  @fieldConfig({
    category: FieldCategory.GEO_INFO,
    infoMsgCode: ['info-general-tooltip.required'],
    validation: [
      {
        errorMsgCode: 'validation-general.required',
        required: true,
      },
    ],
  })
  //#endregion
  public verticalSrsName!: string;

  //#region DEM: dataType
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:dataType',
    queryableField: 'mc:dataType',
    pycswField: 'pycsw:dataType',
  })
  @catalogDB({
    column: {
      name: 'data_type',
      type: 'data_type',
      nullable: false,
    },
  })
  @tsTypes({
    mappingType: TsTypes.DEM_DATATYPE,
  })
  @graphql({
    nullable: false,
  })
  @fieldConfig({
    category: FieldCategory.GENERAL,
    isAutoGenerated: true,
  })
  //#endregion
  public dataType!: DEMDataType;

  //#region DEM: areaOrPoint
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:areaOrPoint',
    queryableField: 'mc:areaOrPoint',
    pycswField: 'pycsw:areaOrPoint',
  })
  @catalogDB({
    column: {
      name: 'area_or_point',
      type: 'pixel_type',
      nullable: false,
    },
  })
  @tsTypes({
    mappingType: TsTypes.STRING,
  })
  @graphql({
    nullable: false,
  })
  @fieldConfig({
    category: FieldCategory.GENERAL,
    isAutoGenerated: true,
  })
  //#endregion
  public areaOrPoint!: AreaOrPoint;

  //#region DEM: noDataValue
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:noDataValue',
    queryableField: 'mc:noDataValue',
    pycswField: 'pycsw:noDataValue',
  })
  @catalogDB({
    column: {
      name: 'no_data_value',
      type: 'numeric',
      nullable: false,
    },
  })
  @tsTypes({
    mappingType: TsTypes.NUMBER,
  })
  @graphql({
    nullable: false,
  })
  @fieldConfig({
    category: FieldCategory.GENERAL,
    infoMsgCode: ['info-general-tooltip.required'],
    validation: [
      {
        errorMsgCode: 'validation-general.required',
        required: true,
      },
    ],
  })
  //#endregion
  public noDataValue!: number;

  //#region DEM: productStatus
  @pycsw({
    profile: 'mc_dem',
    xmlElement: 'mc:productStatus',
    queryableField: 'mc:productStatus',
    pycswField: 'pycsw:productStatus',
  })
  @catalogDB({
    column: {
      name: 'product_status',
      type: 'product_status',
      default: RecordStatus.UNPUBLISHED,
      nullable: false,
    },
  })
  @tsTypes({
    mappingType: TsTypes.RECORD_STATUS,
  })
  @graphql({
    nullable: true,
  })
  @fieldConfig({
    category: FieldCategory.MAIN,
    default: RecordStatus.UNPUBLISHED,
    isLifecycleEnvolved: true,
  })
  //#endregion
  public productStatus: RecordStatus = RecordStatus.UNPUBLISHED;

  //#region DEM: dispalyPath
  @catalogDB({
    column: {
      name: 'display_path',
      type: 'text',
      nullable: false,
    },
  })
  @tsTypes({
    mappingType: TsTypes.STRING,
  })
  //#endregion
  public displayPath!: string;
  //#endregion

  public static getPyCSWMapping(prop: string): IPYCSWMapping | undefined {
    return getPyCSWMapping<LayerDemMetadata>(new LayerDemMetadata(), prop);
  }

  public static getCatalogDBMapping(prop: string): ICatalogDBMapping | undefined {
    return getCatalogDBMapping<LayerDemMetadata>(new LayerDemMetadata(), prop);
  }

  public static getFieldConfig(prop: string): IFieldConfigInfo | undefined {
    return getFieldConfig<LayerDemMetadata>(new LayerDemMetadata(), prop);
  }

  public static getPyCSWMappings(): IPropPYCSWMapping[] {
    const ret = [];
    const layer = new LayerDemMetadata();
    for (const prop in layer) {
      const pycswMap = getPyCSWMapping<LayerDemMetadata>(layer, prop);
      if (pycswMap) {
        ret.push({
          prop: prop,
          ...pycswMap,
        });
      }
    }
    return ret;
  }

  public static getCatalogDBMappings(): IPropCatalogDBMapping[] {
    const ret = [];
    const layer = new LayerDemMetadata();
    for (const prop in layer) {
      const catalogDbMap = getCatalogDBMapping<LayerDemMetadata>(layer, prop);
      const tsTypesMap = getTsTypesMapping<LayerDemMetadata>(layer, prop);
      if (catalogDbMap && tsTypesMap) {
        ret.push({
          prop: prop,
          ...catalogDbMap,
          ...tsTypesMap,
        });
      }
    }
    return ret;
  }

  public static getFieldConfigs(): IPropFieldConfigInfo[] {
    const ret = [];
    const layer = new LayerDemMetadata();
    for (const prop in layer) {
      const fieldConfigMap = getFieldConfig<LayerDemMetadata>(layer, prop);
      if (fieldConfigMap) {
        ret.push({
          prop: prop,
          ...fieldConfigMap,
        });
      }
    }
    return ret;
  }
}
