openapi: "3.0.1"
info:
  title: Full Layer metadata definitions
  version: 2.0.0
components:
  schemas:
    fullLayerMetadata:
      type: object
      allOf:
        - $ref: ./updateLayerMetadata.yaml#/components/schemas/updateLayerMetadata
        - properties:
            id:
              type: string
              format: uuid
            displayPath:
              type: string
            transparency:
              type: string
              enum:
              - TRANSPARENT
              - OPAQUE
              description: layer can be transparent or opaque
            tileOutputFormat:
              type: string
              enum:
              - PNG
              - JPEG
              description: Tile creation can be of type png or jpeg
