openapi: "3.0.1"
info:
  title: Full Layer metadata definitions
  version: 2.0.0
components:
  schemas:
    fullLayerMetadata:
      type: object
      allOf:
        - $ref: ./updateLayerMetadata.yaml#/components/schemas/updateLayerMetadata
        - properties:
            id:
              type: string
              format: uuid
            displayPath:
              type: string
            transparency:
              type: string
              enum:
              - TRANSPARENT
              - OPAQUE
              description: layer can be transparent or opaque
            tileOutputFormat:
              type: string
              enum:
              - PNG
              - JPEG
              description: Tile format can be of png or jpeg
            tileMimeFormat:
              type: string
              enum:
              - image/png
              - image/jpeg
              description: Image format associated with content type (mime)
            minResolutionDeg:
              type: number
              minimum: 0.000000167638063430786
              maximum: 0.703125
              format: double
              description:  min resolution of layer in degrees/pixel
            minResolutionMeter:
              type: number
              minimum: 0.0185
              maximum: 78271.52 
              format: double
              description: min (rounded) resolution of layer in meters/pixel
            maxHorizontalAccuracyCE90:
              type: number
              minimum: 0.01
              maximum: 4000
              format: double
              description: minimum Horizontal Accuracy

