openapi: "3.0.1"
info:
  title: Geojson definitions
  version: 1.0.0
components:
  schemas:
    GeometryBase:
      type: object
      description: GeoJSon geometry
      required:
        - type
      externalDocs:
        url: http://geojson.org/geojson-spec.html#geometry-objects
      properties:
        type:
          type: string
          enum:
            - Point
            - LineString
            - Polygon
            - MultiPoint
            - MultiLineString
            - MultiPolygon
          description: the geometry type
          
    Geometry:
      description: GeoJSon geometry
      discriminator:
          propertyName: type
      type: object
      anyOf:
        - $ref: '#/components/schemas/Point'
        - $ref: '#/components/schemas/LineString'
        - $ref: '#/components/schemas/Polygon'
        - $ref: '#/components/schemas/MultiPoint'
        - $ref: '#/components/schemas/MultiLineString'
        - $ref: '#/components/schemas/MultiPolygon'
  
    Point2D:
      type: array
      maxItems: 2
      minItems: 2
      items:
        type: number
        minimum: -180
        maximum: 180
  
    Point:
      type: object
      description: GeoJSon geometry
      externalDocs:
        url: http://geojson.org/geojson-spec.html#id2
      allOf:
        - $ref: "#/components/schemas/GeometryBase"
        - properties:
            coordinates:
              $ref: "#/components/schemas/Point2D"
  
    LineString:
      type: object
      description: GeoJSon geometry
      externalDocs:
        url: http://geojson.org/geojson-spec.html#id3
      allOf:
        - $ref: "#/components/schemas/GeometryBase"
        - properties:
            coordinates:
              type: array
              items:
                $ref: "#/components/schemas/Point2D"
  
    Polygon:
      type: object
      description: GeoJSon geometry
      externalDocs:
        url: http://geojson.org/geojson-spec.html#id4
      allOf:
        - $ref: "#/components/schemas/GeometryBase"
        - properties:
            coordinates:
              type: array
              items:
                type: array
                items:
                  $ref: "#/components/schemas/Point2D"
  
    MultiPoint:
      type: object
      description: GeoJSon geometry
      externalDocs:
        url: http://geojson.org/geojson-spec.html#id5
      allOf:
        - $ref: "#/components/schemas/GeometryBase"
        - properties:
            coordinates:
              type: array
              items:
                $ref: "#/components/schemas/Point2D"
  
    MultiLineString:
      type: object
      description: GeoJSon geometry
      externalDocs:
        url: http://geojson.org/geojson-spec.html#id6
      allOf:
        - $ref: "#/components/schemas/GeometryBase"
        - properties:
            coordinates:
              type: array
              items:
                type: array
                items:
                  $ref: "#/components/schemas/Point2D"
  
    MultiPolygon:
      type: object
      description: GeoJSon geometry
      externalDocs:
        url: http://geojson.org/geojson-spec.html#id6
      allOf:
        - $ref: "#/components/schemas/GeometryBase"
        - properties:
            coordinates:
              type: array
              items:
                type: array
                items:
                  type: array
                  items:
                    $ref: "#/components/schemas/Point2D"
  
    GeometryCollection:
      type: object
      description: GeoJSon geometry collection
      required:
        - type
        - geometries
      externalDocs:
        url: http://geojson.org/geojson-spec.html#geometrycollection
      properties:
        type:
          type: string
          enum:
            - GeometryCollection
          description: custom properties
        geometries:
          type: array
          items:
            $ref: "#/components/schemas/GeometryBase"

    BBox:
      type: array
      minItems: 4
      items:
        type: number
    
    Feature:
      required:
        - type
        - properties
        - geometry
      properties:
        type:
          type: string
          enum: 
            - Feature
        properties:
          type: object
          nullable: true
        geometry:
          type: object
          nullable: true
          oneOf:
            - $ref: "#/components/schemas/GeometryCollection"
            - $ref: "#/components/schemas/Geometry"
        bbox:
          $ref: "#/components/schemas/BBox"

    FeatureCollection:
      type: object
      description: GeoJson Feature collection
      required:
        - type
        - features
      properties:
        type:
          type: string
          enum:
            - FeatureCollection
        features:
          type: array
          items:
            $ref: "#/components/schemas/Feature"
        bbox:
          $ref: "#/components/schemas/BBox"
