openapi: "3.0.1"
info:
  title: Layer metadata definitions
  version: 2.0.0
components:
  schemas:
    insertLayerMetadata:
      type: object
      required:
        - productId
        - productName
        - productVersion
        - productType
        - updateDate
        - resolution
        - accuracyCE90
        - sensorType
        - footprint
        - type
        - sourceDateStart
        - sourceDateEnd
      allOf:
        - $ref: ./updateLayerMetadata.yaml#/components/schemas/updateLayerMetadata

    insertStatusLayerMetadata:
      type: object
      required:
        - ingestionStartDate
        - ingestionEndDate
        - layerTileLocation
      allOf:
        - $ref: ./updateLayerMetadata.yaml#/components/schemas/updateStatusLayerMetadata
