openapi: "3.0.1"
info:
  title: Layer metadata definitions
  version: 2.0.0
components:
  schemas:
    LayerMetadata:
      type: object
      description: layer meta data
      required:
        - type
        - productId
        - productName
        - productVersion
        - productType
        - srsId
        - srsName
        - producerName
        - creationDate
        - ingestionDate
        - updateDate
        - sourceDateStart
        - sourceDateEnd
        - accuracyCE90
        - sensorType
        - region
        - rms
        - scale
        - footprint
      properties:
        type:
          type: string
          description: Layer type raster / 3d / dem
          enum:
            - RECORD_RASTER
            - RECORD_3D
        classification:
          type: string
          description: Permitted roles 
        productId:
          type: string
          description: Layer's external identifier
        productName: 
          type: string
          description: Layer's external name
        productVersion:
          type: string
          description: layer's version
        productType:
          type: string
          description: layer's type might be derived from the first letter
        description: 
          type: string
          description: layer's deascription
        srsId:
          type: string
          description: geo system id
        srsName:
          type: string
          description: geo system name
        producerName:
          type: string
          description: creator name default IDFMU
        creationDate:
          type: string
          description: Creation date
          format: date-time
        ingestionDate:
          type: string
          description: Ingestion date
          format: date-time
        updateDate:
          type: string
          description: Update date
          format: date-time
        sourceDateStart:
          type: string
          description: Oldest imaging date
          format: date-time
        sourceDateEnd:
          type: string
          description: Latest imaging date
          format: date-time
        resolution:
          type: number
          description: Resolution of tiff files
        accuracyCE90:
          type: number
          description: Horizontal Accuracy
        sensorType:
          type: string
          enum:
            - VIS
            - RGB
            - Pan_Sharpen
            - OTHER
          description: The sensor type
        region:
          type: string
          description: Resolution of tiff files
        rms:
          type: number
        scale:
          type: string
        footprint:
          $ref: geojson.yaml#/components/schemas/Geometry
    StatusLayerMetadata:
      type: object
      description: Metadata for layer status
      required:
        - ingestionStartDate
        - ingestionEndDate
        - layerTileLocation
      properties:
        allOf:
          - $ref: "#/components/schemas/LayerMetadata"
          - properties:
              ingestionStartDate:
                type: string
                format: date-time
                description: Ingestion start time date
              ingestionEndDate:
                type: string
                format: date-time
                description: Ingestion end time date
              layerTileLocation:
                type: string
                description: Url of tile location
