openapi: "3.0.1"
info:
  title: Layer metadata definitions
  version: 2.0.0
components:
  schemas:
    productType:
      type: string
      enum:
        - Orthophoto
        - OrthophotoHistory
        - OrthophotoBest
        - RasterMap
        - RasterMapBest
        - RasterAid
        - RasterAidBest
        - RasterVector
        - RasterVectorBest
      description: layer's type might be derived from the first letter  
    updateLayerMetadata:
      type: object
      description: layer meta data
      properties:
        type:
          type: string
          description: Layer type raster / 3d / dem
          enum:
            - RECORD_RASTER
            - RECORD_3D
        classification:
          type: string
          description: Permitted roles 
        productId:
          type: string
          description: Layer's external identifier
          pattern: ^[a-zA-Z0-9_-]+$
        productName: 
          type: string
          description: Layer's external name
        productVersion:
          type: string
          pattern: ^[1-9]\d{0,2}(\.(0|[1-9]\d?))?$
          description: layer's version
        productType:
          $ref: '#/components/schemas/productType'
        productSubType:
          type: string
          description: Layer's sub type
        description: 
          type: string
          description: layer's description
        srsId:
          type: string
          description: geo system id
        srsName:
          type: string
          description: geo system name
        producerName:
          type: string
          description: creator name default IDFMU
        creationDate:
          type: string
          description: Creation date
          format: date-time
        ingestionDate:
          type: string
          description: Ingestion date
          format: date-time
        sourceDateStart:
          type: string
          description: Oldest imaging date
          format: date-time
        sourceDateEnd:
          type: string
          description: Latest imaging date
          format: date-time
        maxResolutionDeg:
          type: number
          minimum: 0.00000009
          maximum: 0.072
          format: double
          description:  max resolution of layer in degrees/pixel
        maxResolutionMeter:
          type: number
          minimum: 0.01
          maximum: 8000
          format: double
          description: max (rounded) resolution of layer in meters/pixel
        minHorizontalAccuracyCE90:
          type: number
          minimum: 0.01
          maximum: 4000
          format: double
          description: minimum Horizontal Accuracy
        sensors:
          type: array
          items:
            type: string
          description: Layer sensors list 
        region:
          type: array
          items:
            type: string
          description: regions included in the layer
        rms:
          type: number
        scale:
          type: integer
          minimum: 0
          maximum: 100000000
        footprint:
          $ref: geojson.yaml#/components/schemas/Geometry
        layerPolygonParts:
          $ref: geojson.yaml#/components/schemas/FeatureCollection
        rawProductData:
          $ref: geojson.yaml#/components/schemas/FeatureCollection
        productBoundingBox:
          type: string
          pattern: "^-?(0|[1-9]\\d*)(\\.\\d*)?,-?(0|[1-9]\\d*)(\\.\\d*)?,-?(0|[1-9]\\d*)(\\.\\d*)?,-?(0|[1-9]\\d*)(\\.\\d*)?$"
          
    updateStatusLayerMetadata:
      type: object
      description: Metadata for layer status
      allOf:
        - $ref: "#/components/schemas/updateLayerMetadata"
        - properties:
            ingestionStartDate:
              type: string
              format: date-time
              description: Ingestion start time date
            ingestionEndDate:
              type: string
              format: date-time
              description: Ingestion end time date
            layerTileLocation:
              type: string
              description: Url of tile location
