openapi: "3.0.1"
info:
  title: Geojson definitions
  version: 1.0.0
servers:
  - url: http://localhost:80/
definitions:
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: string
      message:
        type: string

  Geometry:
    type: object
    description: GeoJSon geometry
    discriminator: type
    required:
      - type
    externalDocs:
      url: http://geojson.org/geojson-spec.html#geometry-objects
    properties:
      type:
        type: string
        enum:
          - Point
          - LineString
          - Polygon
          - MultiPoint
          - MultiLineString
          - MultiPolygon
        description: the geometry type

  Point2D:
    type: array
    maxItems: 2
    minItems: 2
    items:
      type: number

  Point:
    type: object
    description: GeoJSon geometry
    externalDocs:
      url: http://geojson.org/geojson-spec.html#id2
    allOf:
      - $ref: "#/definitions/Geometry"
      - properties:
          coordinates:
            $ref: "#/definitions/Point2D"

  LineString:
    type: object
    description: GeoJSon geometry
    externalDocs:
      url: http://geojson.org/geojson-spec.html#id3
    allOf:
      - $ref: "#/definitions/Geometry"
      - properties:
          coordinates:
            type: array
            items:
              $ref: "#/definitions/Point2D"

  Polygon:
    type: object
    description: GeoJSon geometry
    externalDocs:
      url: http://geojson.org/geojson-spec.html#id4
    allOf:
      - $ref: "#/definitions/Geometry"
      - properties:
          coordinates:
            type: array
            items:
              type: array
              items:
                $ref: "#/definitions/Point2D"

  MultiPoint:
    type: object
    description: GeoJSon geometry
    externalDocs:
      url: http://geojson.org/geojson-spec.html#id5
    allOf:
      - $ref: "#/definitions/Geometry"
      - properties:
          coordinates:
            type: array
            items:
              $ref: "#/definitions/Point2D"

  MultiLineString:
    type: object
    description: GeoJSon geometry
    externalDocs:
      url: http://geojson.org/geojson-spec.html#id6
    allOf:
      - $ref: "#/definitions/Geometry"
      - properties:
          coordinates:
            type: array
            items:
              type: array
              items:
                $ref: "#/definitions/Point2D"

  MultiPolygon:
    type: object
    description: GeoJSon geometry
    externalDocs:
      url: http://geojson.org/geojson-spec.html#id6
    allOf:
      - $ref: "#/definitions/Geometry"
      - properties:
          coordinates:
            type: array
            items:
              type: array
              items:
                type: array
                items:
                  $ref: "#/definitions/Point2D"

  GeometryCollection:
    type: object
    description: GeoJSon geometry collection
    required:
      - type
      - geometries
    externalDocs:
      url: http://geojson.org/geojson-spec.html#geometrycollection
    properties:
      type:
        type: string
        enum:
          - GeometryCollection
        description:
      geometries:
        type: array
        items:
          $ref: "#/definitions/Geometry"

responses:
  Standard500ErrorResponse:
    description: An unexpected error occured.
    schema:
      $ref: "#/definitions/Error"

  BadRequest400ErrorResponse:
    description: The JSON is not valid
    schema:
      $ref: "#/definitions/Error"

  Unauthorized401ErrorResponse:
    description: The request requires an user authentication
    schema:
      $ref: "#/definitions/Error"

  Forbidden403ErrorResponse:
    description: the access is not allowed
    schema:
      $ref: "#/definitions/Error"
