name: publish

on:
  workflow_dispatch:
  release:
    types: [published]
    branches: [master]

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Init nodejs
        uses: MapColonies/shared-workflows/actions/init-npm@init-npm-v1
        with:
          node-version: '20.x'
      - run: npm i -g npm@11.17.0
      - run: npm publish --access public
